### ISSUE TITLE
make it easy to see what colors each palette offers

### ISSUE THREAD

**Issue by rcorty** [leonawicz/legocolors#2]
similar to 

`RColorBrewer::display.brewer.all()`

(for all palettes) and 

`RColorBrewer::display.brewer.pal(n = 8, name = 'Solid')`

for a specific palette

I made one for the first 8 colors of the "solid" palette using:

```
par(bg = 'lightgray', mar = c(4, 2, 4, 2))
plot(x = 1:8, y = rep(0, 8), col = legocolors::legopals$solid[1:8], pch = 15, cex = 6, axes = FALSE, xlab = NA, ylab = NA, main = 'The first 8 colors of the "solid" palette')
```

[first_eight.pdf](https://github.com/leonawicz/legocolors/files/3014374/first_eight.pdf)

and for the entire "solid" palette using:

```
par(bg = 'lightgray', mar = c(4, 2, 4, 2))
plot(x = rep(x = 1:9, each = 9), y = rep(x = 1:9, times = 9), col = c(legocolors::legopals$solid, NA), pch = 15, cex = 6, axes = FALSE, xlab = NA, ylab = NA, main = 'The 80 colors of the "solid" palette')
```

[solid_palette.pdf](https://github.com/leonawicz/legocolors/files/3014355/solid_palette.pdf)

Please feel free to use these

**Comment by leonawicz** [comment]
Sounds good! Thanks for the suggestion. I'll work something in when I get a chance.

To potentially enhance upon the idea as well as connect to the general idea of the package, I think it could be helpful to also allow a palette preview function to take an arbitrary vector of colors (as an alternative input to a Lego palette name) and display the color swatches for the `legocolors` conversion to nearest RGB lego colors.

Especially since these named palettes are merely organizational and not useful as defined palettes for plotting purposes.

Also, I am surprised anyone has even looked at this package! 😄

**Comment by leonawicz** [comment]
New `view_legopal` function displays named package palettes and, even better, a vector of hex color values converted to nearest Lego colors.
